title: Judikael Nedev - Portfolio
author: Judikael Nedev
description: "Portfolio de Judikael Nedev, Admin IT & Développeur Python passionné par l'automatisation, l'IA et les solutions open-source."
url: "https://judikael-nedev.github.io"
github_username: Azrogue
